// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.zhoulei.NettyNIO.protobuf.model;

public final class PersonPro {
  private PersonPro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PresonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Preson)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 age = 2;</code>
     */
    boolean hasAge();
    /**
     * <code>required int32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>required string hir = 3;</code>
     */
    boolean hasHir();
    /**
     * <code>required string hir = 3;</code>
     */
    java.lang.String getHir();
    /**
     * <code>required string hir = 3;</code>
     */
    com.google.protobuf.ByteString
        getHirBytes();

    /**
     * <code>required int64 id = 4;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 4;</code>
     */
    long getId();

    /**
     * <code>repeated int32 list = 5;</code>
     */
    java.util.List<java.lang.Integer> getListList();
    /**
     * <code>repeated int32 list = 5;</code>
     */
    int getListCount();
    /**
     * <code>repeated int32 list = 5;</code>
     */
    int getList(int index);

    /**
     * <code>optional string context = 6;</code>
     */
    boolean hasContext();
    /**
     * <code>optional string context = 6;</code>
     */
    java.lang.String getContext();
    /**
     * <code>optional string context = 6;</code>
     */
    com.google.protobuf.ByteString
        getContextBytes();
  }
  /**
   * Protobuf type {@code Preson}
   */
  public static final class Preson extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Preson)
      PresonOrBuilder {
    // Use Preson.newBuilder() to construct.
    private Preson(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Preson(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Preson defaultInstance;
    public static Preson getDefaultInstance() {
      return defaultInstance;
    }

    public Preson getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Preson(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              hir_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              id_ = input.readInt64();
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                list_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              list_.add(input.readInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                list_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                list_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              context_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhoulei.NettyNIO.protobuf.model.PersonPro.internal_static_Preson_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhoulei.NettyNIO.protobuf.model.PersonPro.internal_static_Preson_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson.class, com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson.Builder.class);
    }

    public static com.google.protobuf.Parser<Preson> PARSER =
        new com.google.protobuf.AbstractParser<Preson>() {
      public Preson parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Preson(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Preson> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>required int32 age = 2;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int HIR_FIELD_NUMBER = 3;
    private java.lang.Object hir_;
    /**
     * <code>required string hir = 3;</code>
     */
    public boolean hasHir() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string hir = 3;</code>
     */
    public java.lang.String getHir() {
      java.lang.Object ref = hir_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hir_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string hir = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHirBytes() {
      java.lang.Object ref = hir_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 4;
    private long id_;
    /**
     * <code>required int64 id = 4;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 id = 4;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int LIST_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Integer> list_;
    /**
     * <code>repeated int32 list = 5;</code>
     */
    public java.util.List<java.lang.Integer>
        getListList() {
      return list_;
    }
    /**
     * <code>repeated int32 list = 5;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated int32 list = 5;</code>
     */
    public int getList(int index) {
      return list_.get(index);
    }

    public static final int CONTEXT_FIELD_NUMBER = 6;
    private java.lang.Object context_;
    /**
     * <code>optional string context = 6;</code>
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string context = 6;</code>
     */
    public java.lang.String getContext() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          context_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string context = 6;</code>
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      name_ = "";
      age_ = 0;
      hir_ = "";
      id_ = 0L;
      list_ = java.util.Collections.emptyList();
      context_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAge()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHir()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, age_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getHirBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, id_);
      }
      for (int i = 0; i < list_.size(); i++) {
        output.writeInt32(5, list_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getContextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getHirBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < list_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(list_.get(i));
        }
        size += dataSize;
        size += 1 * getListList().size();
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getContextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Preson}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Preson)
        com.zhoulei.NettyNIO.protobuf.model.PersonPro.PresonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhoulei.NettyNIO.protobuf.model.PersonPro.internal_static_Preson_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhoulei.NettyNIO.protobuf.model.PersonPro.internal_static_Preson_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson.class, com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson.Builder.class);
      }

      // Construct using com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        hir_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        list_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        context_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhoulei.NettyNIO.protobuf.model.PersonPro.internal_static_Preson_descriptor;
      }

      public com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson getDefaultInstanceForType() {
        return com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson.getDefaultInstance();
      }

      public com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson build() {
        com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson buildPartial() {
        com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson result = new com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.age_ = age_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hir_ = hir_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          list_ = java.util.Collections.unmodifiableList(list_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.list_ = list_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.context_ = context_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson) {
          return mergeFrom((com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson other) {
        if (other == com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasHir()) {
          bitField0_ |= 0x00000004;
          hir_ = other.hir_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (!other.list_.isEmpty()) {
          if (list_.isEmpty()) {
            list_ = other.list_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureListIsMutable();
            list_.addAll(other.list_);
          }
          onChanged();
        }
        if (other.hasContext()) {
          bitField0_ |= 0x00000020;
          context_ = other.context_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasAge()) {
          
          return false;
        }
        if (!hasHir()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhoulei.NettyNIO.protobuf.model.PersonPro.Preson) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>required int32 age = 2;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>required int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 age = 2;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object hir_ = "";
      /**
       * <code>required string hir = 3;</code>
       */
      public boolean hasHir() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string hir = 3;</code>
       */
      public java.lang.String getHir() {
        java.lang.Object ref = hir_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hir_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string hir = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHirBytes() {
        java.lang.Object ref = hir_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hir_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string hir = 3;</code>
       */
      public Builder setHir(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        hir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string hir = 3;</code>
       */
      public Builder clearHir() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hir_ = getDefaultInstance().getHir();
        onChanged();
        return this;
      }
      /**
       * <code>required string hir = 3;</code>
       */
      public Builder setHirBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        hir_ = value;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <code>required int64 id = 4;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 id = 4;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 4;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000008;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 4;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> list_ = java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          list_ = new java.util.ArrayList<java.lang.Integer>(list_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated int32 list = 5;</code>
       */
      public java.util.List<java.lang.Integer>
          getListList() {
        return java.util.Collections.unmodifiableList(list_);
      }
      /**
       * <code>repeated int32 list = 5;</code>
       */
      public int getListCount() {
        return list_.size();
      }
      /**
       * <code>repeated int32 list = 5;</code>
       */
      public int getList(int index) {
        return list_.get(index);
      }
      /**
       * <code>repeated int32 list = 5;</code>
       */
      public Builder setList(
          int index, int value) {
        ensureListIsMutable();
        list_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 list = 5;</code>
       */
      public Builder addList(int value) {
        ensureListIsMutable();
        list_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 list = 5;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, list_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 list = 5;</code>
       */
      public Builder clearList() {
        list_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      private java.lang.Object context_ = "";
      /**
       * <code>optional string context = 6;</code>
       */
      public boolean hasContext() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string context = 6;</code>
       */
      public java.lang.String getContext() {
        java.lang.Object ref = context_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            context_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string context = 6;</code>
       */
      public com.google.protobuf.ByteString
          getContextBytes() {
        java.lang.Object ref = context_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          context_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string context = 6;</code>
       */
      public Builder setContext(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        context_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string context = 6;</code>
       */
      public Builder clearContext() {
        bitField0_ = (bitField0_ & ~0x00000020);
        context_ = getDefaultInstance().getContext();
        onChanged();
        return this;
      }
      /**
       * <code>optional string context = 6;</code>
       */
      public Builder setContextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        context_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Preson)
    }

    static {
      defaultInstance = new Preson(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Preson)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Preson_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Preson_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\"[\n\006Preson\022\014\n\004name\030\001 \002(\t\022\013" +
      "\n\003age\030\002 \002(\005\022\013\n\003hir\030\003 \002(\t\022\n\n\002id\030\004 \002(\003\022\014\n\004" +
      "list\030\005 \003(\005\022\017\n\007context\030\006 \001(\tB0\n#com.zhoul" +
      "ei.NettyNIO.protobuf.modelB\tPersonPro"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Preson_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Preson_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Preson_descriptor,
        new java.lang.String[] { "Name", "Age", "Hir", "Id", "List", "Context", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
